apiVersion: v1
kind: Pod
metadata:
  name: hello-operator-test
spec:
  restartPolicy: Never
  containers:
  - name: hello-operator-test
    image: docker.io/agreene/hello-operator:0.0.1
    imagePullPolicy: Always
    command: ["/go-test.sh"]
    env:
      - name: TEST_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
